const state={time:[],rawSignals:{},displaySignals:{},filename:'',timeCol:'time',channels:[],fs:null,duration:0,annotations:[],beats:[],editingId:null,pendingSelection:null,peaks:[],preprocessing:{baseline:false,highpass_hz:null,lowpass_hz:null,notch_hz:null}};
const labels=['P Wave','QRS','T Wave','Pacemaker Spike','R Peak','Artifact','Abnormal Beat','Graft Activation','Arrhythmia','Custom'];
const $=id=>document.getElementById(id);labels.forEach(x=>{const o=document.createElement('option');o.value=x;o.textContent=x;$('labelSelect').appendChild(o)});
function message(text,type='ok'){ $('messages').innerHTML=`<div class="message ${type}">${escapeHtml(text)}</div>` }
function escapeHtml(s){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[c]))}
function fmt(x){return Number(x).toFixed(4)} function channel(){return $('channelSelect').value} function label(){return $('customLabel').value.trim()||$('labelSelect').value}
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(16)}
function syncChannels(){['channelSelect','annChannel'].forEach(id=>{const e=$(id);e.innerHTML='';state.channels.forEach(c=>{const o=document.createElement('option');o.value=c;o.textContent=c;e.appendChild(o)})})}
function renderMeta(){ $('recordingMeta').innerHTML=state.filename?`<span><b>File</b><br>${escapeHtml(state.filename)}</span><span><b>Format</b><br>${state.sourceFormat||'CSV'}</span><span><b>Samples</b><br>${state.time.length}</span><span><b>Rate</b><br>${state.fs?fmt(state.fs)+' Hz':'unknown'}</span><span><b>Duration</b><br>${fmt(state.duration)} s</span><span><b>Beats</b><br>${state.beats.length}</span>`:'<span>No recording loaded.</span>' }
function redraw(){if(!state.time.length)return;const traces=state.channels.map(c=>({x:state.time,y:state.displaySignals[c]||state.rawSignals[c],mode:'lines',name:c,line:{width:c===channel()?1.8:1}}));const shapes=[];state.annotations.forEach(a=>{if(a.type==='interval')shapes.push({type:'rect',x0:a.start,x1:a.end,y0:0,y1:1,yref:'paper',fillcolor:a.status==='flagged'?'#d94b4b':'#f0a43b',opacity:.18,line:{width:0}});else shapes.push({type:'line',x0:a.time,x1:a.time,y0:0,y1:1,yref:'paper',line:{dash:'dash',width:1.4,color:'#c13a3a'}})});state.beats.forEach(b=>shapes.push({type:'rect',x0:b.start,x1:b.end,y0:0,y1:1,yref:'paper',fillcolor:'#1463d5',opacity:.035,line:{width:0}}));Plotly.react('plot',traces,{margin:{l:55,r:20,t:25,b:45},height:560,dragmode:'select',showlegend:true,shapes,xaxis:{title:'Time (s)',rangeslider:{visible:true}},yaxis:{title:'Amplitude'},hovermode:'closest'},{responsive:true,displaylogo:false});renderAnnotations();renderQC();renderMeta()}
async function loadFile(file){const fd=new FormData();fd.append('file',file);const r=await fetch('/api/analyze',{method:'POST',body:fd});const d=await r.json();if(!r.ok||!d.valid){message(d.error||d.errors?.join(' ')||'Validation failed.','error');return}state.time=d.time;state.rawSignals=d.signals;state.displaySignals=structuredClone(d.signals);state.filename=d.filename;state.timeCol=d.time_col||'time';state.channels=d.signal_cols;state.fs=d.sampling_rate_hz;state.duration=d.duration_s;state.sourceFormat=d.source_format;state.annotations=[];state.beats=[];state.peaks=[];state.preprocessing={baseline:false,highpass_hz:null,lowpass_hz:null,notch_hz:null};syncChannels();renderPreprocess();redraw();message(d.warnings?.length?d.warnings.join(' '):`${d.source_format||'CSV'} recording loaded and validated.`,'ok')}
$('fileInput').addEventListener('change',e=>e.target.files[0]&&loadFile(e.target.files[0]));$('channelSelect').addEventListener('change',redraw);$('annType').addEventListener('change',()=>{const interval=$('annType').value==='interval';$('startInput').disabled=!interval;$('endInput').disabled=!interval;$('timeInput').disabled=interval});
$('loadSample').addEventListener('click',async()=>{const r=await fetch('/sample_data/sample_ecg.csv');const b=await r.blob();loadFile(new File([b],'sample_ecg.csv',{type:'text/csv'}))});
function setSelection(){if(!state.pendingSelection)return;$('startInput').value=fmt(state.pendingSelection.start);$('endInput').value=fmt(state.pendingSelection.end);$('selectionHint').textContent=`Selected ${fmt(state.pendingSelection.start)}–${fmt(state.pendingSelection.end)} s`}
function addOrUpdate(){if(!state.fs){message('Load a recording first.','error');return}const type=$('annType').value,a={label:label(),type,channel:$('annChannel').value,confidence:Number($('confidenceInput').value),notes:$('notesInput').value.trim(),annotator:$('annotator').value.trim(),status:'unreviewed',reviewer:'',review_notes:''};if(!a.label||!a.channel){message('Label and channel are required.','error');return}if(type==='interval'){a.start=Number($('startInput').value);a.end=Number($('endInput').value);if(!(a.end>a.start)||a.start<0||a.end>state.duration){message('Invalid interval bounds.','error');return}}else{a.time=Number($('timeInput').value);if(a.time<0||a.time>state.duration){message('Point must stay within recording bounds.','error');return}}if(!Number.isFinite(a.confidence)||a.confidence<0||a.confidence>1){message('Confidence must be between 0 and 1.','error');return}if(state.editingId){const i=state.annotations.findIndex(x=>x.id===state.editingId);if(i>=0){a.id=state.editingId;state.annotations[i]={...state.annotations[i],...a}}}else state.annotations.push({...a,id:crypto.randomUUID?crypto.randomUUID():hash(Date.now()+Math.random())});state.annotations.sort((x,y)=>(x.start??x.time)-(y.start??y.time));cancelEdit();redraw()}
$('saveAnnotation').addEventListener('click',addOrUpdate);function cancelEdit(){state.editingId=null;$('saveAnnotation').textContent='Add annotation';$('cancelEdit').disabled=true;$('selectionHint').textContent='No selection'}$('cancelEdit').addEventListener('click',cancelEdit);
function editAnnotation(id){const a=state.annotations.find(x=>x.id===id);if(!a)return;state.editingId=id;$('annType').value=a.type;$('annType').dispatchEvent(new Event('change'));$('labelSelect').value=labels.includes(a.label)?a.label:'Custom';$('customLabel').value=labels.includes(a.label)?'':a.label;$('annChannel').value=a.channel;$('startInput').value=a.start??'';$('endInput').value=a.end??'';$('timeInput').value=a.time??'';$('confidenceInput').value=a.confidence;$('notesInput').value=a.notes||'';$('saveAnnotation').textContent='Save changes';$('cancelEdit').disabled=false}
function setStatus(id,status){const a=state.annotations.find(x=>x.id===id);if(a){a.status=status;redraw()}}function duplicateAnnotation(id){const a=state.annotations.find(x=>x.id===id);if(a){const c=structuredClone(a);c.id=crypto.randomUUID?crypto.randomUUID():hash(Date.now()+Math.random());c.status='unreviewed';state.annotations.push(c);redraw()}}function deleteAnnotation(id){state.annotations=state.annotations.filter(a=>a.id!==id);redraw()}
function renderAnnotations(){$('annCount').textContent=state.annotations.length;const e=$('annotationList');e.innerHTML='';if(!state.annotations.length){e.innerHTML='<div class="muted">No annotations yet.</div>';return}state.annotations.forEach(a=>{const loc=a.type==='interval'?`${fmt(a.start)}–${fmt(a.end)} s`:`${fmt(a.time)} s`;const d=document.createElement('div');d.className=`annotation ${a.status}`;d.innerHTML=`<div><div class="ann-title">${escapeHtml(a.label)}</div><div class="ann-meta">${escapeHtml(a.channel)} · ${loc} · confidence ${Number(a.confidence).toFixed(2)} · ${a.status}</div>${a.notes?`<div class="ann-meta">${escapeHtml(a.notes)}</div>`:''}</div><div class="ann-actions"><button class="secondary">Edit</button><button class="secondary">Copy</button><button class="secondary">${a.status==='accepted'?'Flag':'Accept'}</button><button class="secondary">Delete</button></div>`;const b=d.querySelectorAll('button');b[0].onclick=()=>editAnnotation(a.id);b[1].onclick=()=>duplicateAnnotation(a.id);b[2].onclick=()=>setStatus(a.id,a.status==='accepted'?'flagged':'accepted');b[3].onclick=()=>deleteAnnotation(a.id);e.appendChild(d)})}
function renderQC(){const c={accepted:0,flagged:0,unreviewed:0};state.annotations.forEach(a=>c[a.status]++);$('qcSummary').innerHTML=`<div class="qc-item"><strong>${c.accepted}</strong>accepted</div><div class="qc-item"><strong>${c.unreviewed}</strong><span class="warn">unreviewed</span></div><div class="qc-item"><strong>${c.flagged}</strong><span class="error">flagged</span></div>`;if($('beatSummary'))$('beatSummary').textContent=state.beats.length?`${state.beats.length} beat windows`:'No beat segmentation yet'}
$('acceptAll').onclick=()=>{state.annotations.forEach(a=>a.status='accepted');redraw()};$('flagUnreviewed').onclick=()=>{state.annotations.forEach(a=>{if(a.status==='unreviewed')a.status='flagged'});redraw()};
function renderPreprocess(){$('baseline').checked=state.preprocessing.baseline;$('highpass').value=state.preprocessing.highpass_hz??'';$('lowpass').value=state.preprocessing.lowpass_hz??'';$('notch').value=state.preprocessing.notch_hz??''}
$('applyFilters').onclick=async()=>{if(!state.fs){message('Load a recording first.','error');return}const hp=$('highpass').value?Number($('highpass').value):null,lp=$('lowpass').value?Number($('lowpass').value):null,n=$('notch').value?Number($('notch').value):null;for(const c of state.channels){const r=await fetch('/api/filter',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sampling_rate_hz:state.fs,signal:state.rawSignals[c],baseline:$('baseline').checked,highpass_hz:hp,lowpass_hz:lp,notch_hz:n})});const d=await r.json();if(!r.ok){message(d.error,'error');return}state.displaySignals[c]=d.signal}state.preprocessing={baseline:$('baseline').checked,highpass_hz:hp,lowpass_hz:lp,notch_hz:n};$('filterMessage').textContent='Display filters applied; raw data are unchanged.';redraw()};
async function detectPeaks(){if(!state.fs)return message('Load a recording first.','error');const r=await fetch('/api/detect/r-peaks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sampling_rate_hz:state.fs,signal:state.displaySignals[channel()]||state.rawSignals[channel()]})});const d=await r.json();if(!r.ok)return message(d.error,'error');state.peaks=d.peaks;message(`Detected ${d.peaks.length} R-peak candidates.`,'warn')}
$('detectPeaks').onclick=async()=>{await detectPeaks();const c=channel();state.peaks.forEach((idx,i)=>state.annotations.push({id:crypto.randomUUID?crypto.randomUUID():hash(Date.now()+i),label:'R Peak',type:'point',channel:c,time:state.time[idx],confidence:.5,notes:'Auto-detected candidate; review required.',annotator:$('annotator').value.trim(),status:'unreviewed',reviewer:'',review_notes:''}));state.annotations.sort((a,b)=>a.time-b.time);redraw()};
$('segmentBeats').onclick=async()=>{if(!state.fs)return message('Load a recording first.','error');const c=channel();const r=await fetch('/api/segment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({time:state.time,signal:state.displaySignals[c]||state.rawSignals[c],sampling_rate_hz:state.fs,peaks:state.peaks.length?state.peaks:null,pre_s:.35,post_s:.55})});const d=await r.json();if(!r.ok)return message(d.error,'error');state.peaks=d.peaks;state.beats=d.beats;redraw();message(`Segmented ${d.n_beats} beats around detected R peaks.`,'ok')};
$('trainModel').onclick=async()=>{const accepted=state.annotations.filter(a=>a.status==='accepted'&&a.type==='point');if(accepted.length<4)return message('Accept at least four point annotations across two or more labels before training.','warn');const c=channel();const r=await fetch('/api/ml/train',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sampling_rate_hz:state.fs,signal:state.displaySignals[c]||state.rawSignals[c],peaks:state.peaks,annotations:state.annotations})});const d=await r.json();if(!r.ok||!d.trained)return message(d.error||'Model training failed.','error');$('modelStatus').textContent=`Trained on ${d.metrics.n_training_examples} accepted beats · classes: ${d.metrics.classes.join(', ')}`;message('Model trained. Use Suggest uncertain beats to prioritize human review.','ok')};
$('suggestModel').onclick=async()=>{const accepted=state.annotations.filter(a=>a.status==='accepted'&&a.type==='point');if(accepted.length<4)return message('Accept labeled point annotations from at least two classes first.','warn');if(!state.peaks.length)await detectPeaks();const c=channel();const r=await fetch('/api/ml/suggest',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sampling_rate_hz:state.fs,signal:state.displaySignals[c]||state.rawSignals[c],peaks:state.peaks,annotations:state.annotations,top_n:20})});const d=await r.json();if(!r.ok||!d.trained)return message(d.error||'Could not generate model suggestions.','error');const existing=new Set(state.annotations.filter(a=>a.type==='point').map(a=>`${a.channel}:${a.time.toFixed(4)}`));let added=0;d.suggestions.forEach(s=>{const key=`${c}:${s.time_s.toFixed(4)}`;if(existing.has(key))return;state.annotations.push({id:crypto.randomUUID?crypto.randomUUID():hash(Date.now()+s.index),label:s.predicted_label,type:'point',channel:c,time:s.time_s,confidence:s.confidence,notes:`Active-learning candidate; uncertainty=${s.uncertainty.toFixed(3)}. Human review required.`,annotator:$('annotator').value.trim(),status:'unreviewed',reviewer:'',review_notes:''});added++});state.annotations.sort((a,b)=>(a.time??a.start)-(b.time??b.start));redraw();$('modelStatus').textContent=`Ranked ${d.suggestions.length} uncertain beats; added ${added} new candidates.`;message(`Added ${added} model-ranked candidates for review.`,'warn')};
$('exportJson').onclick=()=>{if(!state.filename)return message('Load a recording first.','error');const payload={schema:'electrotrace.annotation/v2',file:state.filename,metadata:{sampling_rate_hz:state.fs,duration_s:state.duration,channels:state.channels,source_format:state.sourceFormat,annotator:$('annotator').value.trim(),source:$('source').value.trim(),preprocessing:state.preprocessing,beat_count:state.beats.length,exported_at:new Date().toISOString()},annotations:state.annotations};download(JSON.stringify(payload,null,2),`${state.filename.replace(/\.[^.]+$/,'')}_annotations.json`,'application/json')};
$('exportCsv').onclick=()=>{if(!state.annotations.length)return message('No annotations to export.','error');const cols=['file','id','type','label','channel','start','end','time','confidence','notes','annotator','status','reviewer','review_notes'];const rows=[cols.join(',')];state.annotations.forEach(a=>rows.push(cols.map(k=>csv(k==='file'?state.filename:a[k]??'')).join(',')));download(rows.join('\n'),`${state.filename.replace(/\.[^.]+$/,'')}_annotations.csv`,'text/csv')};function csv(v){return `"${String(v).replace(/"/g,'""')}"`}function download(text,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('reviewFile').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const other=JSON.parse(await file.text());const b=other.annotations||[],a=state.annotations;const used=new Set();const errs=[];let matches=0;for(const x of a.filter(q=>q.type==='point')){const cand=b.filter(q=>q.type==='point'&&!used.has(q.id)&&q.label===x.label&&Math.abs(q.time-x.time)<=.04);if(cand.length){const y=cand.reduce((p,q)=>Math.abs(q.time-x.time)<Math.abs(p.time-x.time)?q:p);used.add(y.id);matches++;errs.push(Math.abs(y.time-x.time))}}$('agreementResult').innerHTML=`<b>Point agreement</b><br>${matches} matches · ${(100*matches/Math.max(a.filter(q=>q.type==='point').length,b.filter(q=>q.type==='point').length,1)).toFixed(1)}% within 40 ms${errs.length?` · MAE ${(1000*errs.reduce((x,y)=>x+y,0)/errs.length).toFixed(1)} ms`:''}`}catch(err){$('agreementResult').textContent=`Could not read JSON: ${err.message}`}});
$('plot').on('plotly_selected',ev=>{const x=ev?.range?.x;if(x&&x.length===2){state.pendingSelection={start:Math.min(...x),end:Math.max(...x)};setSelection()}});$('plot').on('plotly_click',ev=>{const p=ev?.points?.[0];if(p){$('timeInput').value=fmt(p.x);$('selectionHint').textContent=`Point ${fmt(p.x)} s`}});window.addEventListener('load',()=>{$('annType').dispatchEvent(new Event('change'))});
