const state={time:[],rawSignals:{},displaySignals:{},filename:'',timeCol:'time',channels:[],fs:null,duration:0,annotations:[],beats:[],editingId:null,pendingSelection:null,peaks:[],preprocessing:{baseline:false,highpass_hz:null,lowpass_hz:null,notch_hz:null},sourceFormat:'',recordingId:null};
const labels=['P Wave','QRS','T Wave','Pacemaker Spike','R Peak','Artifact','Abnormal Beat','Graft Activation','Arrhythmia','Custom'];
const $=id=>document.getElementById(id);labels.forEach(x=>{const o=document.createElement('option');o.value=x;o.textContent=x;$('labelSelect')?.appendChild(o)});
function escapeHtml(s){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[c]))}
function message(text,type='ok'){const el=$('messages');if(el)el.innerHTML=`<div class="message ${type}">${escapeHtml(text)}`}
function fmt(x){return Number(x).toFixed(4)} function channel(){return $('channelSelect')?.value||state.channels[0]||''} function label(){return $('customLabel')?.value.trim()||$('labelSelect')?.value||'Custom'}
function hash(s){let h=2166136261;const str=String(s);for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(16)}
function newId(seed){return crypto.randomUUID?crypto.randomUUID():hash(`${Date.now()}-${seed}-${Math.random()}`)}
function syncChannels(){['channelSelect','annChannel'].forEach(id=>{const e=$(id);if(!e)return;e.innerHTML='';state.channels.forEach(c=>{const o=document.createElement('option');o.value=c;o.textContent=c;e.appendChild(o)})})}
function renderMeta(){const e=$('recordingMeta');if(!e)return;e.innerHTML=state.filename?`<span><b>File</b><br>${escapeHtml(state.filename)}</span><span><b>Format</b><br>${escapeHtml(state.sourceFormat||'CSV')}</span><span><b>Samples shown</b><br>${state.time.length.toLocaleString()}</span><span><b>Rate</b><br>${state.fs?fmt(state.fs)+' Hz':'unknown'}</span><span><b>Duration</b><br>${fmt(state.duration)} s</span><span><b>Beats</b><br>${state.beats.length}</span>`:'<span>No recording loaded.</span>'}
function renderQC(){const c={accepted:0,flagged:0,unreviewed:0};state.annotations.forEach(a=>{c[a.status]=(c[a.status]||0)+1});if($('annCount'))$('annCount').textContent=state.annotations.length;if($('qcSummary'))$('qcSummary').innerHTML=`<div class="qc-item"><strong>${c.accepted||0}</strong>accepted</div><div class="qc-item"><strong>${c.unreviewed||0}</strong><span class="warn">unreviewed</span></div><div class="qc-item"><strong>${c.flagged||0}</strong><span class="error">flagged</span></div>`;if($('beatSummary'))$('beatSummary').textContent=state.beats.length?`${state.beats.length} beat windows`:'No beat segmentation yet'}
function renderAnnotations(){const e=$('annotationList');if(!e)return;e.innerHTML='';if(!state.annotations.length){e.innerHTML='<div class="muted">No annotations yet.</div>';return}for(const a of state.annotations){const loc=a.type==='interval'?`${fmt(a.start)}–${fmt(a.end)} s`:`${fmt(a.time)} s`;const d=document.createElement('div');d.className=`annotation ${a.status}`;d.innerHTML=`<div><div class="ann-title">${escapeHtml(a.label)}</div><div class="ann-meta">${escapeHtml(a.channel)} · ${loc} · confidence ${Number(a.confidence).toFixed(2)} · ${escapeHtml(a.status)}</div>${a.notes?`<div class="ann-meta">${escapeHtml(a.notes)}</div>`:''}</div><div class="ann-actions"><button class="secondary">Edit</button><button class="secondary">Copy</button><button class="secondary">${a.status==='accepted'?'Flag':'Accept'}</button><button class="secondary">Delete</button></div>`;const b=d.querySelectorAll('button');b[0].onclick=()=>editAnnotation(a.id);b[1].onclick=()=>duplicateAnnotation(a.id);b[2].onclick=()=>setStatus(a.id,a.status==='accepted'?'flagged':'accepted');b[3].onclick=()=>deleteAnnotation(a.id);e.appendChild(d)}}
function redraw(){if(!state.time.length)return;const traces=state.channels.map(c=>({x:state.time,y:state.displaySignals[c]??state.rawSignals[c],mode:'lines',name:c,line:{width:c===channel()?1.8:1}}));const shapes=[];state.annotations.forEach(a=>{if(a.type==='interval')shapes.push({type:'rect',x0:a.start,x1:a.end,y0:0,y1:1,yref:'paper',fillcolor:a.status==='flagged'?'#d94b4b':'#f0a43b',opacity:.18,line:{width:0}});else shapes.push({type:'line',x0:a.time,x1:a.time,y0:0,y1:1,yref:'paper',line:{dash:'dash',width:1.4,color:'#c13a3a'}})});state.beats.forEach(b=>shapes.push({type:'rect',x0:b.start,x1:b.end,y0:0,y1:1,yref:'paper',fillcolor:'#1463d5',opacity:.035,line:{width:0}}));Plotly.react('plot',traces,{margin:{l:55,r:20,t:25,b:45},height:560,dragmode:'select',showlegend:true,shapes,xaxis:{title:'Time (s)',rangeslider:{visible:true}},yaxis:{title:'Amplitude'},hovermode:'closest'},{responsive:true,displaylogo:false});renderAnnotations();renderQC();renderMeta()}
function resetRecording(){state.annotations=[];state.beats=[];state.peaks=[];state.editingId=null;state.pendingSelection=null;state.preprocessing={baseline:false,highpass_hz:null,lowpass_hz:null,notch_hz:null}}
function setLoadedData(d,filename,format='CSV',durationOverride=null,recordingId=null){state.time=Array.from(d.time||[],Number);state.rawSignals={};for(const [k,v] of Object.entries(d.signals||{}))state.rawSignals[k]=Array.from(v,Number);state.displaySignals=structuredClone(state.rawSignals);state.filename=filename;state.timeCol=d.time_col||'time';state.channels=d.signal_cols||Object.keys(state.rawSignals);state.fs=Number(d.sampling_rate_hz);state.duration=durationOverride!=null?Number(durationOverride):(Number.isFinite(Number(d.duration_s))?Number(d.duration_s):0);state.sourceFormat=format;state.recordingId=recordingId;resetRecording();syncChannels();renderPreprocess();redraw()}
async function loadNativeWindow(file){const fd=new FormData();fd.append('file',file);const r=await fetch('/api/recording',{method:'POST',body:fd});const meta=await r.json();if(!r.ok)throw new Error(meta.error||'Could not store recording');const stop=Math.min(meta.n_samples,10000);const wr=await fetch(`/api/recording/${meta.recording_id}/window?start=0&stop=${stop}`);const d=await wr.json();if(!wr.ok)throw new Error(d.error||'Could not load recording window');setLoadedData(d,file.name,meta.format,meta.duration_s,meta.recording_id);if(window.researchState){window.researchState.recordingId=meta.recording_id;window.researchState.storedMeta=meta;$('storedMeta')&&($('storedMeta').textContent=`Stored ${String(meta.format).toUpperCase()} · ${Number(meta.n_samples).toLocaleString()} samples · ${Number(meta.duration_s).toFixed(2)} s`)}$('windowInfo')&&($('windowInfo').textContent=`Loaded first ${stop.toLocaleString()} samples. Use the research window controls for other ranges.`);message(`${String(meta.format).toUpperCase()} recording loaded in windowed mode.`,'ok')}
async function loadCsv(file){const fd=new FormData();fd.append('file',file);const r=await fetch('/api/analyze',{method:'POST',body:fd});const d=await r.json();if(!r.ok||!d.valid)throw new Error(d.error||d.errors?.join(' ')||'Validation failed');setLoadedData(d,file.name,'CSV');message(d.warnings?.length?d.warnings.join(' '):'CSV recording loaded and validated.','ok')}
async function loadFile(file){try{const ext=file.name.toLowerCase().split('.').pop();if(ext==='csv')await loadCsv(file);else await loadNativeWindow(file)}catch(e){message(e.message,'error')}}
$('fileInput')?.addEventListener('change',e=>e.target.files[0]&&loadFile(e.target.files[0]));$('loadSample')?.addEventListener('click',async()=>{try{const r=await fetch('/sample_data/sample_ecg.csv');const b=await r.blob();await loadCsv(new File([b],'sample_ecg.csv',{type:'text/csv'}))}catch(e){message(e.message,'error')}});$('channelSelect')?.addEventListener('change',redraw);$('annType')?.addEventListener('change',()=>{const interval=$('annType').value==='interval';$('startInput').disabled=!interval;$('endInput').disabled=!interval;$('timeInput').disabled=interval});
function setSelection(){if(!state.pendingSelection)return;$('startInput').value=fmt(state.pendingSelection.start);$('endInput').value=fmt(state.pendingSelection.end);$('selectionHint').textContent=`Selected ${fmt(state.pendingSelection.start)}–${fmt(state.pendingSelection.end)} s`}
function addOrUpdate(){if(!state.fs)return message('Load a recording first.','error');const type=$('annType').value,a={label:label(),type,channel:$('annChannel').value,confidence:Number($('confidenceInput').value),notes:$('notesInput').value.trim(),annotator:$('annotator').value.trim(),status:'unreviewed',reviewer:'',review_notes:''};if(!a.label||!a.channel)return message('Label and channel are required.','error');if(type==='interval'){a.start=Number($('startInput').value);a.end=Number($('endInput').value);if(!Number.isFinite(a.start)||!Number.isFinite(a.end)||!(a.end>a.start)||a.start<0||a.end>state.duration)return message('Invalid interval bounds.','error')}else{a.time=Number($('timeInput').value);if(!Number.isFinite(a.time)||a.time<0||a.time>state.duration)return message('Point must stay within recording bounds.','error')}if(!Number.isFinite(a.confidence)||a.confidence<0||a.confidence>1)return message('Confidence must be between 0 and 1.','error');if(state.editingId){const i=state.annotations.findIndex(x=>x.id===state.editingId);if(i>=0){a.id=state.editingId;state.annotations[i]={...state.annotations[i],...a}}}else state.annotations.push({...a,id:newId(a.time??a.start)});state.annotations.sort((x,y)=>(x.start??x.time)-(y.start??y.time));cancelEdit();redraw()}
$('saveAnnotation')?.addEventListener('click',addOrUpdate);function cancelEdit(){state.editingId=null;$('saveAnnotation').textContent='Add annotation';$('cancelEdit').disabled=true;$('selectionHint').textContent='No selection'}$('cancelEdit')?.addEventListener('click',cancelEdit);
function editAnnotation(id){const a=state.annotations.find(x=>x.id===id);if(!a)return;state.editingId=id;$('annType').value=a.type;$('annType').dispatchEvent(new Event('change'));$('labelSelect').value=labels.includes(a.label)?a.label:'Custom';$('customLabel').value=labels.includes(a.label)?'':a.label;$('annChannel').value=a.channel;$('startInput').value=a.start??'';$('endInput').value=a.end??'';$('timeInput').value=a.time??'';$('confidenceInput').value=a.confidence;$('notesInput').value=a.notes||'';$('saveAnnotation').textContent='Save changes';$('cancelEdit').disabled=false}
function setStatus(id,status){const a=state.annotations.find(x=>x.id===id);if(a){a.status=status;redraw()}}function duplicateAnnotation(id){const a=state.annotations.find(x=>x.id===id);if(a){const c=structuredClone(a);c.id=newId(a.time??a.start);c.status='unreviewed';c.reviewer='';c.review_notes='';state.annotations.push(c);state.annotations.sort((x,y)=>(x.start??x.time)-(y.start??y.time));redraw()}}function deleteAnnotation(id){state.annotations=state.annotations.filter(a=>a.id!==id);if(state.editingId===id)cancelEdit();redraw()}
$('acceptAll')?.addEventListener('click',()=>{state.annotations.forEach(a=>a.status='accepted');redraw()});$('flagUnreviewed')?.addEventListener('click',()=>{state.annotations.forEach(a=>{if(a.status==='unreviewed')a.status='flagged'});redraw()});
function renderPreprocess(){$('baseline').checked=state.preprocessing.baseline;$('highpass').value=state.preprocessing.highpass_hz??'';$('lowpass').value=state.preprocessing.lowpass_hz??'';$('notch').value=state.preprocessing.notch_hz??''}
$('applyFilters')?.addEventListener('click',async()=>{if(!state.fs)return message('Load a recording first.','error');try{const hp=$('highpass').value?Number($('highpass').value):null,lp=$('lowpass').value?Number($('lowpass').value):null,n=$('notch').value?Number($('notch').value):null;for(const c of state.channels){const r=await fetch('/api/filter',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sampling_rate_hz:state.fs,signal:state.rawSignals[c],baseline:$('baseline').checked,highpass_hz:hp,lowpass_hz:lp,notch_hz:n})});const d=await r.json();if(!r.ok)throw new Error(d.error);state.displaySignals[c]=d.signal}state.preprocessing={baseline:$('baseline').checked,highpass_hz:hp,lowpass_hz:lp,notch_hz:n};$('filterMessage').textContent='Display filters applied; raw data are unchanged.';redraw()}catch(e){message(e.message,'error')}});
async function detectPeaks(){if(!state.fs)throw new Error('Load a recording first.');const c=channel();const r=await fetch('/api/detect/r-peaks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sampling_rate_hz:state.fs,signal:state.displaySignals[c]??state.rawSignals[c]})});const d=await r.json();if(!r.ok)throw new Error(d.error);state.peaks=d.peaks;return d}
$('detectPeaks')?.addEventListener('click',async()=>{try{const d=await detectPeaks();const c=channel();state.peaks.forEach(idx=>state.annotations.push({id:newId(idx),label:'R Peak',type:'point',channel:c,time:state.time[idx],confidence:.5,notes:'Auto-detected candidate; review required.',annotator:$('annotator').value.trim(),status:'unreviewed',reviewer:'',review_notes:''}));state.annotations.sort((a,b)=>a.time-b.time);redraw();message(`Detected ${d.peaks.length} R-peak candidates.`,'warn')}catch(e){message(e.message,'error')}});
$('segmentBeats')?.addEventListener('click',async()=>{try{if(!state.fs)throw new Error('Load a recording first.');const c=channel();const r=await fetch('/api/segment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({time:state.time,signal:state.displaySignals[c]??state.rawSignals[c],sampling_rate_hz:state.fs,peaks:state.peaks,pre_s:.35,post_s:.55})});const d=await r.json();if(!r.ok)throw new Error(d.error);state.peaks=d.peaks;state.beats=d.beats;redraw();message(`Segmented ${d.n_beats} beats around detected R peaks.`,'ok')}catch(e){message(e.message,'error')}});
async function trainModel(){if(state.annotations.filter(a=>a.status==='accepted'&&a.type==='point').length<4)throw new Error('Accept at least four point annotations across two or more labels before training.');if(!state.peaks.length)await detectPeaks();const c=channel();const r=await fetch('/api/ml/train',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({time:state.time,sampling_rate_hz:state.fs,signal:state.displaySignals[c]??state.rawSignals[c],peaks:state.peaks,annotations:state.annotations})});const d=await r.json();if(!r.ok||!d.trained)throw new Error(d.error||'Model training failed');return d}
$('trainModel')?.addEventListener('click',async()=>{try{const d=await trainModel();$('modelStatus').textContent=`Trained on ${d.metrics.n_training_examples} accepted beats · classes: ${d.metrics.classes.join(', ')}`;message('Model trained.','ok')}catch(e){message(e.message,'error')}});
$('suggestModel')?.addEventListener('click',async()=>{try{if(state.annotations.filter(a=>a.status==='accepted'&&a.type==='point').length<4)throw new Error('Accept labeled point annotations from at least two classes first.');if(!state.peaks.length)await detectPeaks();const c=channel();const r=await fetch('/api/ml/suggest',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({time:state.time,sampling_rate_hz:state.fs,signal:state.displaySignals[c]??state.rawSignals[c],peaks:state.peaks,annotations:state.annotations,top_n:20})});const d=await r.json();if(!r.ok||!d.trained)throw new Error(d.error||'Could not generate model suggestions');const existing=new Set(state.annotations.filter(a=>a.type==='point').map(a=>`${a.channel}:${Number(a.time).toFixed(4)}`));let added=0;for(const s of d.suggestions){const key=`${c}:${Number(s.time_s).toFixed(4)}`;if(existing.has(key))continue;state.annotations.push({id:newId(s.index),label:s.predicted_label,type:'point',channel:c,time:s.time_s,confidence:s.confidence,notes:`Active-learning candidate; uncertainty=${s.uncertainty.toFixed(3)}. Human review required.`,annotator:$('annotator').value.trim(),status:'unreviewed',reviewer:'',review_notes:''});added++}state.annotations.sort((a,b)=>(a.time??a.start)-(b.time??b.start));redraw();$('modelStatus').textContent=`Ranked ${d.suggestions.length} uncertain beats; added ${added} candidates.`;message(`Added ${added} model-ranked candidates for review.`,'warn')}catch(e){message(e.message,'error')}});
$('exportJson')?.addEventListener('click',()=>{if(!state.filename)return message('Load a recording first.','error');const payload={schema:'electrotrace.annotation/v2',file:state.filename,metadata:{sampling_rate_hz:state.fs,duration_s:state.duration,channels:state.channels,source_format:state.sourceFormat,recording_id:state.recordingId,annotator:$('annotator').value.trim(),source:$('source').value.trim(),preprocessing:state.preprocessing,beat_count:state.beats.length,exported_at:new Date().toISOString()},annotations:state.annotations};download(JSON.stringify(payload,null,2),`${state.filename.replace(/\.[^.]+$/,'')}_annotations.json`,'application/json')});
$('exportCsv')?.addEventListener('click',()=>{if(!state.annotations.length)return message('No annotations to export.','error');const cols=['file','id','type','label','channel','start','end','time','confidence','notes','annotator','status','reviewer','review_notes'];const rows=[cols.join(',')];state.annotations.forEach(a=>rows.push(cols.map(k=>csv(k==='file'?state.filename:a[k]??'')).join(',')));download(rows.join('\n'),`${state.filename.replace(/\.[^.]+$/,'')}_annotations.csv`,'text/csv')});function csv(v){return `"${String(v).replace(/"/g,'""')}"`}function download(text,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('reviewFile')?.addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const other=JSON.parse(await file.text()),b=other.annotations||[],a1=state.annotations.filter(a=>a.type==='point'),a2=b.filter(a=>a.type==='point');let matches=0,errors=[];const used=new Set();for(const a of a1){let best=null;for(const x of a2){if(used.has(x.id)||x.label!==a.label)continue;const err=Math.abs(Number(x.time)-Number(a.time));if(err<=.04&&(!best||err<best.err))best={x,err}}if(best){used.add(best.x.id);matches++;errors.push(best.err)}}const rate=matches/Math.max(a1.length,a2.length,1);$('agreementResult').innerHTML=`<b>Point agreement</b><br>${matches} matches · ${(100*rate).toFixed(1)}% within 40 ms${errors.length?` · mean absolute error ${(1000*errors.reduce((x,y)=>x+y,0)/errors.length).toFixed(1)} ms`:''}`;}catch(err){$('agreementResult').textContent='Could not read annotation JSON: '+err.message}});
window.loadWindowData=function(data){const filename=state.filename,format=state.sourceFormat,id=state.recordingId,duration=state.duration;setLoadedData(data,filename,format,duration,id);message(`Loaded samples ${Number(data.start||0).toLocaleString()}–${(Number(data.stop||0)-1).toLocaleString()}.`,'ok')};
window.addEventListener('load',()=>{$('annType')?.dispatchEvent(new Event('change'));redraw()});
const plotEl=$('plot');if(plotEl){const observer=new MutationObserver(()=>{if(plotEl.data&&!plotEl.__bound){plotEl.on('plotly_selected',ev=>{const pts=ev?.range?.x;if(pts&&pts.length===2){state.pendingSelection={start:Math.min(...pts),end:Math.max(...pts)};setSelection()}});plotEl.on('plotly_click',ev=>{const p=ev?.points?.[0];if(p){$('timeInput').value=fmt(p.x);$('selectionHint').textContent=`Point ${fmt(p.x)} s`;state.pendingSelection=null}});plotEl.__bound=true}});observer.observe(plotEl,{childList:true,subtree:true})}
