const researchState={recordingId:null,storedMeta:null};
function researchMsg(text,type='ok'){const el=$('researchMessage');if(el)el.textContent=text;message(text,type)}

// Large-recording audit: route CSV browser loading through the same persistent
// window path used for EDF/WFDB, avoiding full-trace JSON materialization.
async function loadCsv(file){await loadNativeWindow(file);message('CSV recording stored and loaded in windowed mode.','ok')}
window.loadCsv=loadCsv;

$('storeRecording')?.addEventListener('click',async()=>{
  const file=$('fileInput')?.files?.[0];if(!file)return researchMsg('Choose a recording first.','warn');
  try{const fd=new FormData();fd.append('file',file);const r=await fetch('/api/recording',{method:'POST',body:fd});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not store recording.');researchState.recordingId=d.recording_id;researchState.storedMeta=d;if(window.state){state.recordingId=d.recording_id}if($('storedMeta'))$('storedMeta').textContent=`Stored ${String(d.format).toUpperCase()} · ${Number(d.n_samples).toLocaleString()} samples · ${Number(d.duration_s).toFixed(2)} s`;researchMsg('Recording stored for windowed access and project tracking.','ok')}catch(e){researchMsg(e.message,'error')}});

$('fetchWindow')?.addEventListener('click',async()=>{
  if(!researchState.recordingId)return researchMsg('Store the recording first.','warn');
  try{const start=Math.max(0,Math.floor(Number($('windowStart').value||0)));const stop=Math.max(start+1,Math.floor(Number($('windowStop').value||5000)));const r=await fetch(`/api/recording/${researchState.recordingId}/window?start=${start}&stop=${stop}`);const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not fetch window');if(typeof window.loadWindowData==='function')window.loadWindowData({...d,signal_cols:Object.keys(d.signals||{}),sampling_rate_hz:researchState.storedMeta?.sampling_rate_hz});if($('windowInfo'))$('windowInfo').textContent=`Loaded samples ${d.start.toLocaleString()}–${(d.stop-1).toLocaleString()} (${(d.stop-d.start).toLocaleString()} samples).`;researchMsg('Window loaded. Existing annotation state was reset to protect against mixing recordings.','ok')}catch(e){researchMsg(e.message,'error')}});

$('saveProjectRecording')?.addEventListener('click',async()=>{
  if(!researchState.storedMeta)return researchMsg('Store the recording first.','warn');
  try{const payload={project:$('projectName').value.trim()||'default',recording_id:researchState.recordingId,subject_id:$('subjectId').value.trim()||'unassigned',group:$('groupName').value.trim(),visit:$('visitName').value.trim(),format:researchState.storedMeta.format,sampling_rate_hz:researchState.storedMeta.sampling_rate_hz,duration_s:researchState.storedMeta.duration_s,channels:researchState.storedMeta.channels,source_path:researchState.storedMeta.filename};const r=await fetch('/api/project/recording',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not save project recording');if($('projectCount'))$('projectCount').textContent=`${d.recordings.length} recording(s) in project`;researchMsg('Recording registered in project metadata.','ok')}catch(e){researchMsg(e.message,'error')}});

$('phenotypeAnalysis')?.addEventListener('click',async()=>{
  if(!state.peaks.length)return researchMsg('Detect R peaks first.','warn');
  try{const sig=state.displaySignals[channel()]||state.rawSignals[channel()];const r=await fetch('/api/phenotype',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({time:state.time,signal:sig,r_indices:state.peaks})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Phenotype analysis failed');const h=d.summary.heart_rate_bpm||{},q=d.summary.qrs_width_proxy_s||{};$('phenotypeResult').innerHTML=`<b>${d.summary.n_beats} beats</b> · HR median ${h.median==null?'—':h.median.toFixed(1)} bpm · RR median ${d.summary.rr_prev_s?.median==null?'—':d.summary.rr_prev_s.median.toFixed(3)} s · QRS proxy median ${q.median==null?'—':(q.median*1000).toFixed(1)} ms · tachy ${(100*(d.summary.tachycardia_fraction||0)).toFixed(1)}% · brady ${(100*(d.summary.bradycardia_fraction||0)).toFixed(1)}%`}catch(e){researchMsg(e.message,'error')}});

$('comparePhenotype')?.addEventListener('click',async()=>{try{const a=$('groupAValues').value.split(',').map(Number).filter(Number.isFinite),b=$('groupBValues').value.split(',').map(Number).filter(Number.isFinite);const r=await fetch('/api/statistics/compare',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({group_a:a,group_b:b})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Group comparison failed');const effect=d.cohens_d==null?'undefined (zero pooled variance)':d.cohens_d.toFixed(3);$('statsResult').textContent=`n=${d.n_a}/${d.n_b} · means ${d.mean_a.toFixed(3)} vs ${d.mean_b.toFixed(3)} · Welch p=${d.welch_p.toExponential(3)} · Mann–Whitney p=${d.mann_whitney_p.toExponential(3)} · Cohen's d=${effect}`}catch(e){researchMsg(e.message,'error')}});

$('runBenchmark')?.addEventListener('click',async()=>{try{const payload=JSON.parse($('benchmarkJson').value);const r=await fetch('/api/benchmark',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Benchmark failed');const rf=d.models.random_forest.mean,lr=d.models.logistic_regression.mean;$('benchmarkResult').textContent=`${d.n_samples} samples · ${d.n_subjects} subjects · RF macro-F1 ${(100*rf.macro_f1).toFixed(1)}% · RF balanced accuracy ${(100*rf.balanced_accuracy).toFixed(1)}% · LR macro-F1 ${(100*lr.macro_f1).toFixed(1)}%. Splits: ${d.splitter||'subject-level CV'}.`}catch(e){researchMsg('Benchmark failed: '+e.message,'error')}});
window.addEventListener('load',()=>{if($('projectName'))$('projectName').value='default'});
